/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RenewalRouteImport } from './routes/renewal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ClientLoginRouteImport } from './routes/client.login'
import { Route as ClientDevicesRouteImport } from './routes/client.devices'
import { Route as ClientChannelsRouteImport } from './routes/client.channels'
import { Route as ClientAiSettingsRouteImport } from './routes/client.ai-settings'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminChatLogsRouteImport } from './routes/admin.chat-logs'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as ClientChannelsIndexRouteImport } from './routes/client.channels.index'
import { Route as ClientInboxSlotRouteImport } from './routes/client.inbox.$slot'
import { Route as ClientChannelsPlatformRouteImport } from './routes/client.channels.$platform'
import { Route as AdminClientsIdRouteImport } from './routes/admin.clients.$id'
import { Route as ClientInboxPlatformDeviceRouteImport } from './routes/client.inbox.$platform.$device'
import { Route as ApiPublicN8nClientAiSettingsRouteImport } from './routes/api/public/n8n.client-ai-settings'

const RenewalRoute = RenewalRouteImport.update({
  id: '/renewal',
  path: '/renewal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDevicesRoute = ClientDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => ClientRoute,
} as any)
const ClientChannelsRoute = ClientChannelsRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => ClientRoute,
} as any)
const ClientAiSettingsRoute = ClientAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => ClientRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminChatLogsRoute = AdminChatLogsRouteImport.update({
  id: '/chat-logs',
  path: '/chat-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const ClientChannelsIndexRoute = ClientChannelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientChannelsRoute,
} as any)
const ClientInboxSlotRoute = ClientInboxSlotRouteImport.update({
  id: '/inbox/$slot',
  path: '/inbox/$slot',
  getParentRoute: () => ClientRoute,
} as any)
const ClientChannelsPlatformRoute = ClientChannelsPlatformRouteImport.update({
  id: '/$platform',
  path: '/$platform',
  getParentRoute: () => ClientChannelsRoute,
} as any)
const AdminClientsIdRoute = AdminClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AdminRoute,
} as any)
const ClientInboxPlatformDeviceRoute =
  ClientInboxPlatformDeviceRouteImport.update({
    id: '/inbox/$platform/$device',
    path: '/inbox/$platform/$device',
    getParentRoute: () => ClientRoute,
  } as any)
const ApiPublicN8nClientAiSettingsRoute =
  ApiPublicN8nClientAiSettingsRouteImport.update({
    id: '/api/public/n8n/client-ai-settings',
    path: '/api/public/n8n/client-ai-settings',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/renewal': typeof RenewalRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/chat-logs': typeof AdminChatLogsRoute
  '/admin/login': typeof AdminLoginRoute
  '/client/ai-settings': typeof ClientAiSettingsRoute
  '/client/channels': typeof ClientChannelsRouteWithChildren
  '/client/devices': typeof ClientDevicesRoute
  '/client/login': typeof ClientLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/client/channels/$platform': typeof ClientChannelsPlatformRoute
  '/client/inbox/$slot': typeof ClientInboxSlotRoute
  '/client/channels/': typeof ClientChannelsIndexRoute
  '/api/public/n8n/client-ai-settings': typeof ApiPublicN8nClientAiSettingsRoute
  '/client/inbox/$platform/$device': typeof ClientInboxPlatformDeviceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/renewal': typeof RenewalRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/chat-logs': typeof AdminChatLogsRoute
  '/admin/login': typeof AdminLoginRoute
  '/client/ai-settings': typeof ClientAiSettingsRoute
  '/client/devices': typeof ClientDevicesRoute
  '/client/login': typeof ClientLoginRoute
  '/admin': typeof AdminIndexRoute
  '/client': typeof ClientIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/client/channels/$platform': typeof ClientChannelsPlatformRoute
  '/client/inbox/$slot': typeof ClientInboxSlotRoute
  '/client/channels': typeof ClientChannelsIndexRoute
  '/api/public/n8n/client-ai-settings': typeof ApiPublicN8nClientAiSettingsRoute
  '/client/inbox/$platform/$device': typeof ClientInboxPlatformDeviceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/renewal': typeof RenewalRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/chat-logs': typeof AdminChatLogsRoute
  '/admin/login': typeof AdminLoginRoute
  '/client/ai-settings': typeof ClientAiSettingsRoute
  '/client/channels': typeof ClientChannelsRouteWithChildren
  '/client/devices': typeof ClientDevicesRoute
  '/client/login': typeof ClientLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/client/': typeof ClientIndexRoute
  '/admin/clients/$id': typeof AdminClientsIdRoute
  '/client/channels/$platform': typeof ClientChannelsPlatformRoute
  '/client/inbox/$slot': typeof ClientInboxSlotRoute
  '/client/channels/': typeof ClientChannelsIndexRoute
  '/api/public/n8n/client-ai-settings': typeof ApiPublicN8nClientAiSettingsRoute
  '/client/inbox/$platform/$device': typeof ClientInboxPlatformDeviceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/dashboard'
    | '/login'
    | '/renewal'
    | '/admin/activity'
    | '/admin/chat-logs'
    | '/admin/login'
    | '/client/ai-settings'
    | '/client/channels'
    | '/client/devices'
    | '/client/login'
    | '/admin/'
    | '/client/'
    | '/admin/clients/$id'
    | '/client/channels/$platform'
    | '/client/inbox/$slot'
    | '/client/channels/'
    | '/api/public/n8n/client-ai-settings'
    | '/client/inbox/$platform/$device'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/renewal'
    | '/admin/activity'
    | '/admin/chat-logs'
    | '/admin/login'
    | '/client/ai-settings'
    | '/client/devices'
    | '/client/login'
    | '/admin'
    | '/client'
    | '/admin/clients/$id'
    | '/client/channels/$platform'
    | '/client/inbox/$slot'
    | '/client/channels'
    | '/api/public/n8n/client-ai-settings'
    | '/client/inbox/$platform/$device'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/dashboard'
    | '/login'
    | '/renewal'
    | '/admin/activity'
    | '/admin/chat-logs'
    | '/admin/login'
    | '/client/ai-settings'
    | '/client/channels'
    | '/client/devices'
    | '/client/login'
    | '/admin/'
    | '/client/'
    | '/admin/clients/$id'
    | '/client/channels/$platform'
    | '/client/inbox/$slot'
    | '/client/channels/'
    | '/api/public/n8n/client-ai-settings'
    | '/client/inbox/$platform/$device'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RenewalRoute: typeof RenewalRoute
  ApiPublicN8nClientAiSettingsRoute: typeof ApiPublicN8nClientAiSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/renewal': {
      id: '/renewal'
      path: '/renewal'
      fullPath: '/renewal'
      preLoaderRoute: typeof RenewalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/login': {
      id: '/client/login'
      path: '/login'
      fullPath: '/client/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/devices': {
      id: '/client/devices'
      path: '/devices'
      fullPath: '/client/devices'
      preLoaderRoute: typeof ClientDevicesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/channels': {
      id: '/client/channels'
      path: '/channels'
      fullPath: '/client/channels'
      preLoaderRoute: typeof ClientChannelsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/ai-settings': {
      id: '/client/ai-settings'
      path: '/ai-settings'
      fullPath: '/client/ai-settings'
      preLoaderRoute: typeof ClientAiSettingsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/chat-logs': {
      id: '/admin/chat-logs'
      path: '/chat-logs'
      fullPath: '/admin/chat-logs'
      preLoaderRoute: typeof AdminChatLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/channels/': {
      id: '/client/channels/'
      path: '/'
      fullPath: '/client/channels/'
      preLoaderRoute: typeof ClientChannelsIndexRouteImport
      parentRoute: typeof ClientChannelsRoute
    }
    '/client/inbox/$slot': {
      id: '/client/inbox/$slot'
      path: '/inbox/$slot'
      fullPath: '/client/inbox/$slot'
      preLoaderRoute: typeof ClientInboxSlotRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/channels/$platform': {
      id: '/client/channels/$platform'
      path: '/$platform'
      fullPath: '/client/channels/$platform'
      preLoaderRoute: typeof ClientChannelsPlatformRouteImport
      parentRoute: typeof ClientChannelsRoute
    }
    '/admin/clients/$id': {
      id: '/admin/clients/$id'
      path: '/clients/$id'
      fullPath: '/admin/clients/$id'
      preLoaderRoute: typeof AdminClientsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/client/inbox/$platform/$device': {
      id: '/client/inbox/$platform/$device'
      path: '/inbox/$platform/$device'
      fullPath: '/client/inbox/$platform/$device'
      preLoaderRoute: typeof ClientInboxPlatformDeviceRouteImport
      parentRoute: typeof ClientRoute
    }
    '/api/public/n8n/client-ai-settings': {
      id: '/api/public/n8n/client-ai-settings'
      path: '/api/public/n8n/client-ai-settings'
      fullPath: '/api/public/n8n/client-ai-settings'
      preLoaderRoute: typeof ApiPublicN8nClientAiSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminChatLogsRoute: typeof AdminChatLogsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminClientsIdRoute: typeof AdminClientsIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminChatLogsRoute: AdminChatLogsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminClientsIdRoute: AdminClientsIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientChannelsRouteChildren {
  ClientChannelsPlatformRoute: typeof ClientChannelsPlatformRoute
  ClientChannelsIndexRoute: typeof ClientChannelsIndexRoute
}

const ClientChannelsRouteChildren: ClientChannelsRouteChildren = {
  ClientChannelsPlatformRoute: ClientChannelsPlatformRoute,
  ClientChannelsIndexRoute: ClientChannelsIndexRoute,
}

const ClientChannelsRouteWithChildren = ClientChannelsRoute._addFileChildren(
  ClientChannelsRouteChildren,
)

interface ClientRouteChildren {
  ClientAiSettingsRoute: typeof ClientAiSettingsRoute
  ClientChannelsRoute: typeof ClientChannelsRouteWithChildren
  ClientDevicesRoute: typeof ClientDevicesRoute
  ClientLoginRoute: typeof ClientLoginRoute
  ClientIndexRoute: typeof ClientIndexRoute
  ClientInboxSlotRoute: typeof ClientInboxSlotRoute
  ClientInboxPlatformDeviceRoute: typeof ClientInboxPlatformDeviceRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientAiSettingsRoute: ClientAiSettingsRoute,
  ClientChannelsRoute: ClientChannelsRouteWithChildren,
  ClientDevicesRoute: ClientDevicesRoute,
  ClientLoginRoute: ClientLoginRoute,
  ClientIndexRoute: ClientIndexRoute,
  ClientInboxSlotRoute: ClientInboxSlotRoute,
  ClientInboxPlatformDeviceRoute: ClientInboxPlatformDeviceRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RenewalRoute: RenewalRoute,
  ApiPublicN8nClientAiSettingsRoute: ApiPublicN8nClientAiSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
